Style/Documentation:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/SafeNavigation:
  Enabled: false
Metrics/MethodLength:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
AllCops:
  NewCops: enable
Naming/MethodName:
  Enabled: false
Style/ZeroLengthPredicate:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/NumericPredicate:
  Enabled: false